/*
	wcfServiceExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "wcfServiceExample.h"
#import "wcfService.h"

@implementation wcfServiceExample

- (void)run {
	// Create the service
	wcfService* service = [wcfService service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	

	// Returns wcfKeyValueItem*. 
	[service xCheckLogin:self action:@selector(xCheckLoginHandler:) xemail: @"" xpassword: @"" EquipmentType: @""];

	// Returns NSMutableArray*. 
	[service xGetCommunity:self action:@selector(xGetCommunityHandler:) xemail: @"" xpassword: @"" EquipmentType: @""];

	// Returns NSString*.
	[service xisupdate_ipad2:self action:@selector(xisupdate_ipadHandler:) version: @""];

	// Returns NSString*. 
	[service xisupdate_tablet:self action:@selector(xisupdate_tabletHandler:) version: @""];

	// Returns NSString*. 
	[service xSendGetPasswordMail:self action:@selector(xSendGetPasswordMailHandler:) xemail: @"" EquipmentType: @""];
}

	

// Handle the response from xCheckLogin.
		
- (void) xCheckLoginHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the wcfKeyValueItem* result
		wcfKeyValueItem* result = (wcfKeyValueItem*)value;
	NSLog(@"xCheckLogin returned the value: %@", result);
			
}
	

// Handle the response from xGetCommunity.
		
- (void) xGetCommunityHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"xGetCommunity returned the value: %@", result);
			
}
	

// Handle the response from xisupdate_ipad.
		
- (void) xisupdate_ipadHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xisupdate_ipad returned the value: %@", result);
			
}
	

// Handle the response from xisupdate_tablet.
		
- (void) xisupdate_tabletHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xisupdate_tablet returned the value: %@", result);
			
}
	

// Handle the response from xSendGetPasswordMail.
		
- (void) xSendGetPasswordMailHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"xSendGetPasswordMail returned the value: %@", result);
			
}
	

@end
		